### ISSUE TITLE
Refine privacy policy

### ISSUE THREAD

**Issue by realguystuff** [softwcoins/privacy-policy#1]
This privacy policy is made from iubenda and it needs refinement and additions to this Policy. Heroku and Amazon Web Services (AWS) is shown in the generator recommendations but it is made for Pro, which we don't have.

**Comment by aryanraj2713** [comment]
@realguystuff Is the issue still open?
if so, I can contribute.

**Comment by KendallDoesCoding** [comment]
Yes, but we have stopped work on the project, I believe, but I'm unsure, @shourgamer2 please confirm.

cc: @ykhokhaneshiya @aryanraj2713

**Comment by shourgamer2** [comment]
Well this project is not good I will delete it due to the fact it's pretty much impossible and useless to make this but you guys can help me on the what language project i will not quit that
